/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 21 16:04:35 GMT 2022
 */

package org.apache.tika.io;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import org.apache.tika.io.TaggedIOException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockIOException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TaggedIOException_ESTest extends TaggedIOException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IOException iOException0 = mock(IOException.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(iOException0).getMessage();
      TaggedIOException taggedIOException0 = new TaggedIOException(iOException0, (Object) null);
      Object object0 = taggedIOException0.getTag();
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException();
      TaggedIOException taggedIOException0 = null;
      try {
        taggedIOException0 = new TaggedIOException((IOException) null, mockIOException0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tika.io.TaggedIOException", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException();
      TaggedIOException taggedIOException0 = new TaggedIOException(mockIOException0, mockIOException0);
      Object object0 = taggedIOException0.getTag();
      assertSame(object0, mockIOException0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MockIOException mockIOException0 = new MockIOException();
      TaggedIOException taggedIOException0 = new TaggedIOException(mockIOException0, mockIOException0);
      IOException iOException0 = taggedIOException0.getCause();
      assertSame(mockIOException0, iOException0);
  }
}
